### ISSUE TITLE
Advanced tab illegal argument

### ISSUE THREAD

**Issue by jackjt8** [alexhliu/ChunkyClPlugin#4]
Opening the Advanced tab prior to loading chunks causes an illegal argument exception.

```
Unchecked exception in render manager
java.lang.IllegalArgumentException: Pointer may not point to null objects
	at org.jocl.Pointer.to(Pointer.java:509)
	at chunkycl.GpuRayTracer.rayTrace(GpuRayTracer.java:624)
	at chunkycl.RenderManagerCl.previewRender(RenderManagerCl.java:264)
	at chunkycl.RenderManagerCl.run(RenderManagerCl.java:203)
```

**Comment by alexhliu** [comment]
Should be fixed in 3b4a66d.
